<?php
/**
 * Created by PhpStorm.
 * User: grand
 * Date: 05-Mar-21
 * Time: 10:53
 */

namespace app\models;

use emcodepro\mvc\UserModel;

class User extends UserModel
{
    public $username;
    public $email;
    public $password;
    public $confirmPassword;

    public static function tableName(): string
    {
        return 'users';
    }

    public static function findOne(array $where)
    {
        return parent::findOne($where); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            'username' => [self::RULE_REQUIRED],
            'email' => [self::RULE_REQUIRED, self::RULE_EMAIL, [self::RULE_UNIQUE, 'class' => self::class]],
            'password' => [self::RULE_REQUIRED, [self::RULE_MIN, 'min' => 6], [self::RULE_MAX, 'max' => 24]],
            'confirmPassword' => [self::RULE_REQUIRED, [self::RULE_MATCH, 'match' => 'password']]
        ];
    }

    public function labels(): array
    {
        return [
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'confirmPassword' => 'Confirm Password'
        ];
    }

    public function register()
    {
        return $this->save();
    }

    public static function attributes(): array
    {
        return ['username', 'email', 'password'];
    }

    public static function primaryKey()
    {
        return 'id';
    }
}